name: Thing to me to do
description: Say here thing to me to do
labels: [me]
body:
  - type: textarea
    id: description
    attributes:
      label: "Describe what you want to me do."
    validations:
      required: true

  - type: dropdown
    id: spanish
    attributes:
      label: "Are you spanish?"
      options:
       - "True"
       - "False"
       
       

  - type: dropdown
    id: discord
    attributes:
      label: "Are you in contact with my discord?"
      options:
        - "Yes "
        - "No "
    validations:
      required: true

 
